#
# Makefile for the video capture/playback device drivers.
#

obj-y += wmt-vid.o
obj-y += sensors/

g_wmt_v4l2_tv_decoder-objs    += tv_decoder/tv-device.o tv_decoder/wmt-tv-decoder.o 
obj-$(CONFIG_WMT_V4L2_TV_DECODER) += g_wmt_v4l2_tv_decoder.o




