/*++
	linux/include/linux/videodev2_wmt.h

	Copyright (c) 2013  WonderMedia Technologies, Inc.

	This program is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License as published by the Free Software Foundation,
	either version 2 of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
	PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	You should have received a copy of the GNU General Public License along with
	this program.  If not, see <http://www.gnu.org/licenses/>.

	WonderMedia Technologies, Inc.
	10F, 529, Chung-Cheng Road, Hsin-Tien, Taipei 231, R.O.C.
--*/
#ifndef __LINUX_VIDEODEV2_WMT_H
#define __LINUX_VIDEODEV2_WMT_H

#include <linux/videodev2.h>

#define WMT_V4L2_CID_CAMERA_SCENEMODE		0
#define WMT_V4L2_CID_CAMERA_WHITEBALANCE	1
#define WMT_V4L2_CID_CAMERA_ANTIBANDING		2
#define WMT_V4L2_CID_CAMERA_FLASH		3
#define WMT_V4L2_CID_CAMERA_EXPOSURE		4
#define WMT_V4L2_CID_HFLIP			5
#define WMT_V4L2_CID_VFLIP			6

/* CID extensions */
#define V4L2_CID_CAMERA_SCENE_MODE		(V4L2_CID_PRIVATE_BASE+0)
enum v4l2_scene_mode {
	SCENE_MODE_BASE = 0,
	SCENE_MODE_AUTO = 0,
	SCENE_MODE_NIGHTSHOT,
	SCENE_MODE_PORTRAIT,
	SCENE_MODE_BACK_LIGHT,
	SCENE_MODE_LANDSCAPE,
	SCENE_MODE_SPORTS,
	SCENE_MODE_PARTY_INDOOR,
	SCENE_MODE_BEACH_SNOW,
	SCENE_MODE_SUNSET,
	SCENE_MODE_DUSK_DAWN,
	SCENE_MODE_FALL_COLOR,
	SCENE_MODE_FIREWORKS,
	SCENE_MODE_TEXT,
	SCENE_MODE_CANDLE_LIGHT,
	SCENE_MODE_MAX,
};

#define V4L2_CID_CAMERA_FLASH_MODE		(V4L2_CID_PRIVATE_BASE+1)
enum v4l2_flash_mode {
	FLASH_MODE_BASE = 0,
	FLASH_MODE_OFF = 0,
	FLASH_MODE_AUTO,
	FLASH_MODE_ON,
	FLASH_MODE_TORCH,
	FLASH_MODE_STROBE,
	FLASH_MODE_MAX,
};

#define V4L2_CID_CAMERA_ISO			(V4L2_CID_PRIVATE_BASE+2)
enum v4l2_iso_mode {
	ISO_AUTO = 0,
	ISO_50,
	ISO_100,
	ISO_200,
	ISO_400,
	ISO_800,
	ISO_1600,
	ISO_SPORTS,
	ISO_NIGHT,
	ISO_MOVIE,
	ISO_MAX,
};

#define V4L2_CID_CAMERA_METERING		(V4L2_CID_PRIVATE_BASE+3)
enum v4l2_metering_mode {
	METERING_BASE = 0,
	METERING_MATRIX,
	METERING_CENTER,
	METERING_SPOT,
	METERING_MAX,
};

#define V4L2_CID_CAMERA_WDR			(V4L2_CID_PRIVATE_BASE+4)
enum v4l2_wdr_mode {
	WDR_OFF,
	WDR_ON,
	WDR_MAX,
};

#define V4L2_CID_CAMERA_ANTI_SHAKE		(V4L2_CID_PRIVATE_BASE+5)
enum v4l2_anti_shake_mode {
	ANTI_SHAKE_OFF,
	ANTI_SHAKE_STILL_ON,
	ANTI_SHAKE_MOVIE_ON,
	ANTI_SHAKE_MAX,
};

#define V4L2_CID_CAMERA_FOCUS_MODE		(V4L2_CID_PRIVATE_BASE+6)
enum v4l2_focusmode {
	FOCUS_MODE_AUTO = 0,
	FOCUS_MODE_MACRO,
	FOCUS_MODE_FACEDETECT,
	FOCUS_MODE_AUTO_DEFAULT,
	FOCUS_MODE_MACRO_DEFAULT,
	FOCUS_MODE_FACEDETECT_DEFAULT,
	FOCUS_MODE_INFINITY,
	FOCUS_MODE_FIXED,
	FOCUS_MODE_CONTINUOUS,
	FOCUS_MODE_CONTINUOUS_PICTURE,
	FOCUS_MODE_CONTINUOUS_PICTURE_MACRO,
	FOCUS_MODE_CONTINUOUS_VIDEO,
	FOCUS_MODE_TOUCH,
	FOCUS_MODE_MAX,
	FOCUS_MODE_DEFAULT = (1 << 8),
};

#define V4L2_CID_CAMERA_AUTO_FOCUS_RESULT	(V4L2_CID_PRIVATE_BASE+7)
enum v4l2_focusresult {
	FOCUS_RESULT_FOCUSING = 0,
	FOCUS_RESULT_SUCCEED,
	FOCUS_RESULT_FAILED,
};

#define V4L2_CID_CAMERA_FOCUS_POSITION_X	(V4L2_CID_PRIVATE_BASE+8)
#define V4L2_CID_CAMERA_FOCUS_POSITION_Y	(V4L2_CID_PRIVATE_BASE+9)

#define V4L2_CID_CAMERA_FLASH_MODE_AUTO		(V4L2_CID_PRIVATE_BASE+10)

// V4L2_CID_BRIGHTNESS
enum v4l2_ev_mode {
	EV_MINUS_4	= -4,
	EV_MINUS_3	= -3,
	EV_MINUS_2	= -2,
	EV_MINUS_1	= -1,
	EV_DEFAULT	= 0,
	EV_PLUS_1	= 1,
	EV_PLUS_2	= 2,
	EV_PLUS_3	= 3,
	EV_PLUS_4	= 4,
	EV_MAX,
};

// V4L2_CID_DO_WHITE_BALANCE
enum v4l2_wb_mode {
	WHITE_BALANCE_BASE = 0,
	WHITE_BALANCE_AUTO = 0,
	WHITE_BALANCE_INCANDESCENCE,
	WHITE_BALANCE_FLUORESCENT,
	WHITE_BALANCE_DAYLIGHT,
	WHITE_BALANCE_CLOUDY,
	WHITE_BALANCE_TWILIGHT,
	WHITE_BALANCE_SHADE,
	WHITE_BALANCE_MAX,
};

// V4L2_CID_CONTRAST
enum v4l2_contrast_mode {
	CONTRAST_MINUS_2 = 0,
	CONTRAST_MINUS_1,
	CONTRAST_DEFAULT,
	CONTRAST_PLUS_1,
	CONTRAST_PLUS_2,
	CONTRAST_MAX,
};

// V4L2_CID_SATURATION
enum v4l2_saturation_mode {
	SATURATION_MINUS_2 = 0,
	SATURATION_MINUS_1,
	SATURATION_DEFAULT,
	SATURATION_PLUS_1,
	SATURATION_PLUS_2,
	SATURATION_MAX,
};

// V4L2_CID_SHARPNESS
enum v4l2_sharpness_mode {
	SHARPNESS_MINUS_2 = 0,
	SHARPNESS_MINUS_1,
	SHARPNESS_DEFAULT,
	SHARPNESS_PLUS_1,
	SHARPNESS_PLUS_2,
	SHARPNESS_MAX,
};

// V4L2_CID_EXPOSURE
enum v4l2_exposure_mode {
	EXPOSURE_MINUS_4,
	EXPOSURE_MINUS_3,
	EXPOSURE_MINUS_2 = -2,
	EXPOSURE_MINUS_1 = -1,
	EXPOSURE_DEFAULT = 0,
	EXPOSURE_PLUS_1  = 1,
	EXPOSURE_PLUS_2  = 2,
	EXPOSURE_PLUS_3,
	EXPOSURE_PLUS_4,
	EXPOSURE_MAX
};

#endif /* #ifndef __LINUX_VIDEODEV2_WMT_H */
