
s_wmt_batt_ug31xx-objs += \
	 uG31xx_API.o \
	 ug31xx_i2c.o \
	 ug31xx_gauge.o \
	 uG31xx_API_Measurement.o \
	 uG31xx_API_Otp.o \
	 uG31xx_API_System.o \
	 uG31xx_API_Backup.o \
	 uG31xx_API_Capacity.b \

obj-m += s_wmt_batt_ug31xx.o

