#
# Makefile for the Sensor driver
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_INPUT_SENSOR) += gsensor.o
obj-y += sensor.o 
obj-$(CONFIG_WMT_SENSOR_KXTE9) += kxte9_gsensor/
obj-$(CONFIG_WMT_SENSOR_MC3230) += mc3230_gsensor/
obj-$(CONFIG_WMT_SENSOR_DMARD08) += dmard08_gsensor/
obj-$(CONFIG_WMT_SENSOR_DMARD06) += dmard06_gsensor/
obj-$(CONFIG_WMT_SENSOR_MMA7660) += mma7660_gsensor/
obj-$(CONFIG_WMT_SENSOR_ISL29023) += isl29023_lsensor/
obj-$(CONFIG_WMT_SENSOR_CM3232) += cm3232/
obj-$(CONFIG_WMT_SENSOR_CM3232) += stk3310/
obj-$(CONFIG_WMT_SENSOR_DMARD10) += dmard10_gsensor/
obj-$(CONFIG_WMT_SENSOR_MXC622X) += mxc622x_gsensor/
obj-$(CONFIG_WMT_SENSOR_MMC328x) += mmc328x_msensor/
#obj-$(CONFIG_WMT_SENSOR_CM3232) += cm3232/cm3232.o
obj-$(CONFIG_WMT_GYRO_L3G4200D) += l3g4200d_gyro/
obj-$(CONFIG_WMT_SENSOR_US5182) += us5182_lpsensor/
obj-$(CONFIG_WMT_SENSOR_MMA8452Q) += mma8452q_gsensor/
obj-$(CONFIG_WMT_SENSOR_STK8312) += stk8312_gsensor/
obj-$(CONFIG_WMT_SENSOR_KIONIX) += kionix_gsensor/